name: Update Google Reviews

on:
  schedule:
    # Daily at 02:15 UTC (adjust as desired)
    - cron: '15 2 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch reviews (Place ID preferred, fallback to Maps URL)
        shell: pwsh
        env:
          GOOGLE_PLACES_API_KEY: ${{ secrets.GOOGLE_PLACES_API_KEY }}
          GOOGLE_PLACE_ID: ${{ secrets.GOOGLE_PLACE_ID }}
          GOOGLE_MAPS_URL: ${{ secrets.GOOGLE_MAPS_URL }}
        run: |
          if ($env:GOOGLE_PLACES_API_KEY -and $env:GOOGLE_PLACE_ID) {
            ./scripts/fetch-google-reviews.ps1 -ApiKey $env:GOOGLE_PLACES_API_KEY -PlaceId $env:GOOGLE_PLACE_ID -OutputPath data/reviews.json -Language it -Max 6
          } elseif ($env:GOOGLE_PLACES_API_KEY -and $env:GOOGLE_MAPS_URL) {
            ./scripts/fetch-from-maps-url.ps1 -ApiKey $env:GOOGLE_PLACES_API_KEY -MapsUrl $env:GOOGLE_MAPS_URL -OutputPath data/reviews.json -Language it
          } else {
            Write-Host "[reviews] Skipping: required secrets missing"
          }

      - name: Commit changes if any
        shell: bash
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/reviews.json
            git commit -m "chore(reviews): update Google reviews [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
