name: Update Instagram Media

on:
  schedule:
    # Daily at 02:30 UTC
    - cron: '30 2 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-instagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get token from file or secret
        id: token
        shell: pwsh
        run: |
          if (Test-Path ".instagram-token") {
            $data = Get-Content ".instagram-token" | ConvertFrom-Json
            echo "token=$($data.token)" >> $env:GITHUB_OUTPUT
          } else {
            echo "token=${{ secrets.IG_ACCESS_TOKEN }}" >> $env:GITHUB_OUTPUT
          }

      - name: Fetch Instagram media
        shell: pwsh
        run: |
          if (-not "${{ steps.token.outputs.token }}") { throw "Missing token" }
          if (-not "${{ secrets.IG_USER_ID }}") { throw "Missing IG_USER_ID secret" }
          ./scripts/fetch-instagram-media.ps1 -AccessToken "${{ steps.token.outputs.token }}" -UserId "${{ secrets.IG_USER_ID }}" -OutputPath data/instagram.json -Limit 12

      - name: Commit changes if any
        shell: bash
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/instagram.json
            git commit -m "chore(instagram): update media feed [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi

