name: Refresh Instagram Token

on:
  schedule:
    - cron: '0 0 1 * *'  # First day of every month at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  refresh-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Refresh and save token
        shell: pwsh
        run: |
          $token = "${{ secrets.IG_ACCESS_TOKEN }}"
          $uri = "https://graph.instagram.com/refresh_access_token?grant_type=ig_refresh_token&access_token=$token"
          
          try {
            $response = Invoke-RestMethod -Method GET -Uri $uri
            $newToken = $response.access_token
            $expiresIn = $response.expires_in
            
            # Save to file
            @{
              token = $newToken
              refreshed = (Get-Date -Format "o")
              expiresIn = $expiresIn
            } | ConvertTo-Json | Out-File -FilePath ".instagram-token" -Encoding utf8
            
            Write-Host "✓ Token refreshed and saved"
            Write-Host "Expires in: $([math]::Round($expiresIn / 86400)) days"
          } catch {
            Write-Error "Failed: $($_.Exception.Message)"
            exit 1
          }

      - name: Commit new token
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .instagram-token
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: refresh Instagram token [skip ci]" && git push)

